name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: "maven"

      - name: Run tests with coverage
        run: mvn clean verify

      - name: jacoco-badge-generator
        uses: cicirello/jacoco-badge-generator@v2.11.0
        with:
          generate-coverage-badge: true
          generate-branches-badge: true
          coverage-label: lines
          branches-label: branches

      - name: Commit the badge (if it changed)
        run: |
          if [[ `git status --porcelain` ]]; then
            git config --global user.name 'Alex Rothuis'
            git config --global user.email 'arothuis@users.noreply.github.com'
            git add -A
            git commit -m "Autogenerated JaCoCo coverage badge"
            git push
          fi
